version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing node modules
      - npm install
      - echo Finished installing node modules
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'build'